#!/bin/bash
# https://dev.to/krzysztofkaczy9/do-you-really-need-husky-247b

export PATH=$PATH:/usr/local/go/bin

RED="\033[1;31m"
GREEN="\033[1;32m"
NC="\033[0m"

linter_exit_code=1

npx lint-staged

linter_exit_code=$?
if [ $linter_exit_code -ne 0 ]
then
  echo "${RED} X Linter errors have occurred ${NC}"
  exit 1
else
  echo "${GREEN} ✔ Linter didn't find any errors ${NC}"
  exit 0
fi
