name: CI

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm install && pnpm install -g codecov

      - name: Lint codebase
        run: pnpm lint

      - name: Test codebase
        run: pnpm test

      - name: Code coverage
        run: pnpm coverage-gh
      
      - name: Upload coverage reports
        uses: codecov/codecov-action@v1
